### ISSUE TITLE
SCRIPT ERROR: @ts-adminmenu/server/server.lua:59: attempt to index a nil value (local 'xPlayer')

### ISSUE THREAD

**Issue by sherlinjacob** [tony-stark-17/ts-adminmenu#14]
![ts](https://user-images.githubusercontent.com/105943751/169589588-01d71b1a-6160-4c7b-8182-b463774dc282.PNG)

**Comment by tony-stark-17** [comment]
Update the adminmenu and check

**Comment by sherlinjacob** [comment]
yesterday i did download and  check

**Comment by sherlinjacob** [comment]
we need to put steam as identifier? or we can put license as identifier?

**Comment by tony-stark-17** [comment]
You can put any

**Comment by sherlinjacob** [comment]
but still same error. after restarting its okay but the issue is when each admins login to the server needs to restart the script.

**Comment by sherlinjacob** [comment]
how to fix this?

**Comment by tony-stark-17** [comment]
let me check this

**Comment by tony-stark-17** [comment]
Check the latest update

**Comment by sherlinjacob** [comment]
tried still same error.

**Comment by tony-stark-17** [comment]
send screenshot

**Comment by SYNOGIM** [comment]
The same one i just sent first.

**Comment by sherlinjacob** [comment]
the same one i just sent first

**Comment by tony-stark-17** [comment]
Send again I want to check the line number

**Comment by sherlinjacob** [comment]
![err](https://user-images.githubusercontent.com/105943751/169854365-ac79e57b-4e53-4b76-b566-c873210a6076.png)

**Comment by sherlinjacob** [comment]
client side i am not getting any error

**Comment by tony-stark-17** [comment]
I told you to update it and you didn't -_-

**Comment by tony-stark-17** [comment]
the line no. does not match

**Comment by SYNOGIM** [comment]
Ho ok i will try again and let you know.
