### ISSUE TITLE
causing UI lag after few minutes of usage.

### ISSUE THREAD

**Issue by Harry755** [tony-stark-17/ts-adminmenu#15]

**Comment by tony-stark-17** [comment]
That is more like an issue with menuv

**Comment by tony-stark-17** [comment]
I am planning to change it from menuv to something like RageUI etc. It will increase ms in client on opening menu but i think it is better to change it from menuv

**Comment by Harry755** [comment]
ohk bro 
please - re-release or update after u converted it
its a nice menu

**Comment by tony-stark-17** [comment]
Enroute to Scaleform UI
