### ISSUE TITLE
The menu doesn't load until I restart the script

### ISSUE THREAD

**Issue by Chiqu1** [tony-stark-17/ts-adminmenu#16]
![unknown](https://user-images.githubusercontent.com/90169400/170893721-290159a3-5852-4ce8-a584-c64c3d9cbe44.png)
![unknown](https://user-images.githubusercontent.com/90169400/170893726-64790b15-21ff-4cc3-acd2-9f8fd78ce8b2.png)

**Comment by tony-stark-17** [comment]
show the line

**Comment by Chiqu1** [comment]
![imagen_2022-05-29_235234859](https://user-images.githubusercontent.com/90169400/170908466-e0bf1e85-e0b0-49f2-afeb-fdf4dc89baa6.png)

**Comment by tony-stark-17** [comment]
Which ESX Do you use?

**Comment by tony-stark-17** [comment]
Fixed!
