### ISSUE TITLE
CheckAllowed doesn't work

### ISSUE THREAD

**Issue by LABNetwork1** [tony-stark-17/ts-adminmenu#18]
I am testing the admin menu and the permission check only works on the client side

**Comment by tony-stark-17** [comment]
The client and server check function is the same -_-

**Comment by LABNetwork1** [comment]
I know but for some reason the verification is working on the client and not on the server

**Comment by tony-stark-17** [comment]
I can't help you without more details

**Comment by LABNetwork1** [comment]
I will try to see better what is going on

**Comment by LABNetwork1** [comment]
![image](https://user-images.githubusercontent.com/106167115/176421164-e8702e74-486f-478b-be8f-8d6a7ecea8c6.png)
is this correct?

**Comment by tony-stark-17** [comment]
Yes

**Comment by tony-stark-17** [comment]
![image](https://user-images.githubusercontent.com/76168122/176426546-8e4d0baa-f1e2-4472-a8d5-a140f5bb8790.png)

**Comment by tony-stark-17** [comment]
Check perms using this
