### ISSUE TITLE
how to give access using lic (full access ) 

### ISSUE THREAD

**Issue by Capy1174** [tony-stark-17/ts-adminmenu#19]
no docs or description about useage of ace or admin pers

**Comment by tony-stark-17** [comment]
![image](https://user-images.githubusercontent.com/76168122/193281804-0bedad42-6d19-413b-87f3-ec92379628d9.png)
This is self explanatory

**Comment by tony-stark-17** [comment]
Just add the identifier in the users table if you want only for a single character <-- Multicharacter Case
If you don't use multicharacter then just add the license instead of steam:abcd or char1:abcd

**Comment by Capy1174** [comment]
will use license:213232 like this or with out lic prefix coz i tried all ways but still does not rending anything in menu

**Comment by Capy1174** [comment]
and u need to give admin and fullacess both?

**Comment by tony-stark-17** [comment]
> 

With license:21345 if u don't use multicharacter
Secondly you have to give TSAdmin.Admin to open menu and the rest as you wish

**Comment by Capy1174** [comment]
i am using multichar now i have to use steam identifier ?

**Comment by tony-stark-17** [comment]
copy the identifier from users table and paste

**Comment by Capy1174** [comment]
ok
