### ISSUE TITLE
sql error

### ISSUE THREAD

**Issue by ghost** [tony-stark-17/ts-adminmenu#3]
![Screenshot_1](https://user-images.githubusercontent.com/75763087/160875882-f92b270b-41f6-4ffc-b8b2-c9f677d82819.png)

**Comment by tony-stark-17** [comment]
I recommend you comment that part of the code since I didnt implement an integrated prop spawner

**Comment by tony-stark-17** [comment]
It just triggers a diferent prop spawner resource which I will be removing and work on integrating

**Comment by FRANK-Infinity** [comment]
> ![Screenshot_1](https://user-images.githubusercontent.com/75763087/160875882-f92b270b-41f6-4ffc-b8b2-c9f677d82819.png)

can you check your discord?
